import random
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter
import numpy as np

nltk.download('punkt')

def codeWordGen(csvFilepath):
    df = pd.read_csv(csvFilepath, usecols=[1])
    allWords = []
    wordsInRange = []
    for sentence in df.iloc[:, 0].dropna():
        allWords.extend(word_tokenize(sentence.lower()))
    wordFreq = Counter(allWords)
    freqs = list(wordFreq.values())
    bounds = np.mean(freqs)
    #Bounds = np.percentile(freqs, 50)
    # upperBound = freqs[int(n * 0.6)]

    for word, freq in wordFreq.items():
        if freq == int(bounds):
        #if freq >= Bounds and freq <= Bounds:
            wordsInRange.append(word)

    return wordsInRange

def codeWordAssign(secretMessage, wordsInRange):
    messageWords = secretMessage.split()
    aDict = {}
    values = []
    for word in messageWords:
        index = random.randint(0, len(wordsInRange) - 1)
        codeWord = wordsInRange.pop(index)
        aDict[word] = codeWord
        values.append(codeWord)
    return aDict, values
      
    # for loop iterating thru items in messageWords
    # for every item in messageWords, gen randInt between 0 and len(wordsInRange)
    # assign the item in wordsInRange at the index generated by randInt to code word 1
    # repeat
    
csvFilepath = "cleaned_data.csv"
print(codeWordGen(csvFilepath))
