import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter
import numpy as np
import random

nltk.download('punkt')
def codeWordGen(csvFilepath):
    df = pd.read_csv(csvFilepath)
    allWords = []
    for sentence in df.dropna():
        allWords.extend(word_tokenize(sentence.lower()))
    wordFreq = Counter(allWords)
    freqs = list(wordFreq.values())
    meanFreq = np.mean(freqs)
    stdDev = np.std(freqs)
    wordsInRange = [word for word, freq in wordFreq.items() if meanFreq - stdDev <= freq <= meanFreq + stdDev]
    return wordsInRange
csvFilepath = ""
codeWordGen(csvFilepath)

def codeWordAssign(secretMessage, wordsInRange):
    messageWords = secretMessage.split()
    aDict = {}
    keys = []
    values = []
    for item in secretMessage:
        keys += secretMessage[item]
    for item in messageWords:
        index = random.randInt(0, len(wordsInRange)-1)
        codeWord = wordsInRange[index]
        values += codeWord
        wordsInRange.remove(codeWord)
    for i in range(len(keys)):
        aDict[keys[i]] = values[i]
    return aDict, values


    # for loop iterating thru items in messageWords
    # for every item in messageWords, gen randInt between 0 and len(wordsInRange)
    # assign the item in wordsInRange at the index generated by randInt to code word 1
    # repeat



secretMessage = "hot dogs"